version: '3.8'

services:
  # API Backend Node.js
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: makemelearn_api
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://makemelearn_user:MakeMeLearn2025!SecurePass@host.docker.internal:5432/makemelearn
      CORS_ORIGIN: https://makemelearn.fr,https://inscription.makemelearn.fr
      RATE_LIMIT_WINDOW_MS: 900000
      RATE_LIMIT_MAX_REQUESTS: 100
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      # Traefik configuration
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      
      # API endpoint sur inscription.makemelearn.fr
      - "traefik.http.routers.makemelearn-api.rule=Host(`inscription.makemelearn.fr`)"
      - "traefik.http.routers.makemelearn-api.entrypoints=websecure"
      - "traefik.http.routers.makemelearn-api.tls=true"
      - "traefik.http.routers.makemelearn-api.tls.certresolver=myresolver"
      - "traefik.http.services.makemelearn-api.loadbalancer.server.port=3000"
      
      # Redirection HTTP vers HTTPS
      - "traefik.http.routers.makemelearn-api-insecure.rule=Host(`inscription.makemelearn.fr`)"
      - "traefik.http.routers.makemelearn-api-insecure.entrypoints=web"
      - "traefik.http.routers.makemelearn-api-insecure.middlewares=redirect-to-https"
      
      # Headers security
      - "traefik.http.middlewares.makemelearn-api-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.makemelearn-api-headers.headers.sslredirect=true"
      - "traefik.http.routers.makemelearn-api.middlewares=makemelearn-api-headers"

  # Frontend statique
  frontend:
    image: nginx:alpine
    container_name: makemelearn_frontend
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - traefik-public
    restart: unless-stopped
    labels:
      # Traefik configuration pour le frontend
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      
      # Frontend sur makemelearn.fr
      - "traefik.http.routers.makemelearn-frontend.rule=Host(`makemelearn.fr`) || Host(`www.makemelearn.fr`)"
      - "traefik.http.routers.makemelearn-frontend.entrypoints=websecure"
      - "traefik.http.routers.makemelearn-frontend.tls=true"
      - "traefik.http.routers.makemelearn-frontend.tls.certresolver=myresolver"
      - "traefik.http.services.makemelearn-frontend.loadbalancer.server.port=80"
      
      # Redirection HTTP vers HTTPS
      - "traefik.http.routers.makemelearn-frontend-insecure.rule=Host(`makemelearn.fr`) || Host(`www.makemelearn.fr`)"
      - "traefik.http.routers.makemelearn-frontend-insecure.entrypoints=web"
      - "traefik.http.routers.makemelearn-frontend-insecure.middlewares=redirect-to-https"
      
      # Redirect www to non-www
      - "traefik.http.middlewares.makemelearn-redirect-www.redirectregex.regex=^https://www\\.makemelearn\\.fr/(.*)"
      - "traefik.http.middlewares.makemelearn-redirect-www.redirectregex.replacement=https://makemelearn.fr/$${1}"
      - "traefik.http.routers.makemelearn-frontend.middlewares=makemelearn-redirect-www"
      
      # Middleware de redirection HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  traefik-public:
    external: true